### ISSUE TITLE
build-ios.sh Macos Monterey error Luajit 2.1.0-beta3

### ISSUE THREAD

**Issue by alexlovar** [rampantpixels/lua_lib#1]
Hi, the script is not longer works on macos 12.3.1
i change the path for the correct developer sdk but
repeat this error multiple times .........
clang: warning: no such sysroot directory: 'Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk' [-Wmissing-sysroot]
clang: warning: optimization flag '-fomit-frame-pointer' is not supported for target 'armv7' [-Wignored-optimization-argument]
clang: warning: no such sysroot directory: 'Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk' [-Wmissing-sysroot]
clang: warning: optimization flag '-fomit-frame-pointer' is not supported for target 'armv7' [-Wignored-optimization-argument]
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
CC        luajit.o
clang: warning: no such sysroot directory: 'Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk' [-Wmissing-sysroot]
clang: warning: optimization flag '-fomit-frame-pointer' is not supported for target 'armv7' [-Wignored-optimization-argument]
luajit.c:9:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [luajit.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [amalg] Error 2
make: *** [amalg] Error 2
mv: rename ./src/libluajit.a to ./build/libluajitA7.a: No such file or directory
/Library/Developer/CommandLineTools/usr/bin/make -C src clean
